# Generated by Django 4.1.1 on 2022-12-03 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sportsapp', '0003_fixture'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='teamAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='teamID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsapp.team'),
        ),
        migrations.AlterField(
            model_name='member',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Avaliability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliable', models.BooleanField(default=False)),
                ('fixtureID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsapp.fixture')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
