# Generated by Django 4.1.1 on 2022-12-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsapp', '0004_member_teamadmin_alter_member_teamid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
