# Generated by Django 4.1.1 on 2022-12-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsapp', '0005_alter_fixture_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
